---
title: "Feature Reduction Math five-class Classification"
author: "Qianhui Yu"
date: "12/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Five-level Classification for Math

```{r five-level classification for Math}
# load data
math_full = read.csv2(file = "../data/math-full.csv", header = TRUE)
# Feature reduction and Generate 3 different inputs
a_math_five_reduction = subset(math_full, select = -c(school, G3, pass_math, traveltime, nursery, famsup, internet, Pstatus, sex, Fedu, schoolsup, Medu, address, health, guardian, activities, paid, Walc)) 
b_math_five_reduction = subset(math_full, select = -c(school, G2, G3, pass_math, traveltime, nursery, famsup, internet, Pstatus, sex, Fedu, schoolsup, Medu, address, health, guardian, activities, paid, Walc)) 
c_math_five_reduction = subset(math_full, select = -c(school, G1, G2, G3, pass_math, traveltime, nursery, famsup, internet, Pstatus, sex, Fedu, schoolsup, Medu, address, health, guardian, activities, paid, Walc)) 
library(rminer)

# 10-fold cross validation 
K = c("kfold", 10)
# Method 1: Decision Tree
# execute 20 runs of a DT classification for 3 inputs
DT_amf_reduction = mining(five_math~., a_math_five_reduction, model="dt", Runs=20, method=K)
DT_bmf_reduction = mining(five_math~., b_math_five_reduction, model="dt", Runs=20, method=K)
DT_cmf_reduction = mining(five_math~., c_math_five_reduction, model="dt", Runs=20, method=K)

# Can we plot the desicion tree from DT?
# plot(DT_amf_reduction@object[1])

# Method 2: Random Forest
RF_amf_reduction = mining(five_math~., a_math_five_reduction, model="randomForest", Runs=20, method=K)
RF_bmf_reduction = mining(five_math~., b_math_five_reduction, model="randomForest", Runs=20, method=K)
RF_cmf_reduction = mining(five_math~., c_math_five_reduction, model="randomForest", Runs=20, method=K)

# Method 3: NN(mlpe: multilayer perceptron ensemble)
NN_amf_reduction = mining(five_math~., a_math_five_reduction, model = "mlpe", Runs=20, method=K)
NN_bmf_reduction = mining(five_math~., b_math_five_reduction, model = "mlpe", Runs=20, method=K)
NN_cmf_reduction = mining(five_math~., c_math_five_reduction, model = "mlpe", Runs=20, method=K)

# Method 4: SVM
SVM_amf_reduction = mining(five_math~., a_math_five_reduction, model = "svm", Runs=20, method=K)
SVM_bmf_reduction = mining(five_math~., b_math_five_reduction, model = "svm", Runs=20, method=K)
SVM_cmf_reduction = mining(five_math~., c_math_five_reduction, model = "svm", Runs=20, method=K)

# Method 5: NV: Naive Predictor(baseline)

# Method 6: LR (not for binary classification)
# LR_amf_reduction = mining(G3~., math, model = "lm", Runs=20, method=K)
# print(mean(LR_amf_reduction$error) / nrow(math))

# plot figure
# plot(LR_amf_reduction[["object"]][["cv.fit"]])


```
## Print PCC results
```{r print accuracy results}
print(mean(DT_amf_reduction$error))
print(mean(DT_bmf_reduction$error))
print(mean(DT_cmf_reduction$error))
print(mean(RF_amf_reduction$error))
print(mean(RF_bmf_reduction$error))
print(mean(RF_cmf_reduction$error))
print(mean(NN_amf_reduction$error))
print(mean(NN_bmf_reduction$error))
print(mean(NN_cmf_reduction$error))
print(mean(SVM_amf_reduction$error))
print(mean(SVM_bmf_reduction$error))
print(mean(SVM_cmf_reduction$error))                      

```


## Save Models
```{r save models}
model_dir = "../Models/Math/Binary"
# save all models
savemodel(DT_amf_reduction, paste(model_dir, "/dt_amf_reduction.model", sep = ""))
savemodel(DT_bmf_reduction, paste(model_dir, "/dt_bmf_reduction.model", sep = ""))
savemodel(DT_cmf_reduction, paste(model_dir, "/dt_cmf_reduction.model", sep = ""))
savemodel(RF_amf_reduction, paste(model_dir, "/rf_amf_reduction.model", sep = ""))
savemodel(RF_bmf_reduction, paste(model_dir, "/rf_bmf_reduction.model", sep = ""))
savemodel(RF_cmf_reduction, paste(model_dir, "/rf_cmf_reduction.model", sep = ""))
savemodel(NN_amf_reduction, paste(model_dir, "/nn_amf_reduction.model", sep = ""))
savemodel(NN_bmf_reduction, paste(model_dir, "/nn_bmf_reduction.model", sep = ""))
savemodel(NN_cmf_reduction, paste(model_dir, "/nn_cmf_reduction.model", sep = ""))
savemodel(SVM_amf_reduction, paste(model_dir, "/svm_amf_reduction.model", sep = ""))
savemodel(SVM_bmf_reduction, paste(model_dir, "/svm_bmf_reduction.model", sep = ""))
savemodel(SVM_cmf_reduction, paste(model_dir, "/svm_cmf_reduction.model", sep = ""))
```